language: python
python:
  - "3.5"
  - "3.6"

install:
  - "pip install --upgrade pip"
  - "pip install -e . --upgrade --upgrade-strategy=only-if-needed"
  - "pipenv install -r requirements.txt"
  - 'pipenv install --deploy --system --dev'

script:
  - 'pipenv run main.py'
