language: python
python:
  - "3.5"
  - "3.6"

install:
  - "pip install --upgrade pip"
  - "pip install -r ./requirements.txt"
  - 'pipenv install --deploy --system --dev'

script:
  - 'pipenv run main.py'
